import cv2
import numpy as np
import h5py
import pandas as pd
import json
import os
import argparse
from tqdm import tqdm
import io
import imageio
from scipy.io import loadmat
import scipy.io as scio
from scipy import interpolate
from scipy import signal


parser = argparse.ArgumentParser()
# Data setting
parser.add_argument("--dataset_name", default="PURE", type=str)
parser.add_argument("--video_dir", default=None, type=str)
parser.add_argument("--json_dir", default=None, type=str)
parser.add_argument("--landmark_dir", default=None, type=str)
parser.add_argument("--h5_dir", default=None, type=str)
parser.add_argument("--store_size", default=None, type=int)
parser.add_argument(
    "--preview_frames",
    default=2,
    type=int,
    help="Save crop previews for the first N frames of each video. 0 disables previews.",
)


def get_subfolders(folder: str):
    # Get the full paths of the immediate subdirectories in a folder
    if not os.path.isdir(folder):
        raise ValueError(f"{folder} is not a valid folder path.")

    subfolders = [os.path.join(folder, name) for name in os.listdir(folder) if os.path.isdir(os.path.join(folder, name))]

    return subfolders


def my_interp(data, original_len, target_len):
    # Create target index
    original_indices = np.linspace(0, 1, original_len)
    target_indices = np.linspace(0, 1, target_len)

    # Use linear interpolation
    interpolated_data = np.interp(target_indices, original_indices, data)
    return interpolated_data


def read_ground_truth(dataset_name, total_num_frame, json_path):
    if dataset_name == "UBFC-rPPG":
        bvp, hr, video_t = np.loadtxt(json_path)
        return video_t, bvp, hr

    elif dataset_name == "PURE":
        with open(json_path, "r") as infile:
            gt_data = json.load(infile)
        # Read video timestamps
        video_t = []
        for sample in gt_data["/Image"]:
            video_t.append(sample["Timestamp"])
        # Read oximeter data
        wave_t = []
        bvp = []
        hr = []
        for sample in gt_data["/FullPackage"]:
            wave_t.append(sample["Timestamp"])
            bvp.append(sample["Value"]["waveform"])
            hr.append(sample["Value"]["pulseRate"])
        video_t = np.array(video_t) * 1e-9
        wave_t = np.array(wave_t) * 1e-9
        bvp = np.array(bvp)
        bvp = np.interp(video_t, wave_t, bvp)
        hr = np.array(hr)
        hr = np.interp(video_t, wave_t, hr)
        return video_t, bvp, hr

    elif dataset_name == "BUAA":
        data_path = os.path.join(json_path, "PPGData.mat")
        Num = total_num_frame

        pulse = scio.loadmat(data_path)["PPG"]["data"][0][0]
        pulse = np.array(np.array(pulse).astype("float32")).reshape(-1)

        Time = np.linspace(0, Num, len(pulse))
        CSI_Time = np.linspace(0, Num, Num)

        t = interpolate.splrep(Time, pulse)
        pulse_csi = interpolate.splev(CSI_Time, t)

        LPF = 0.7  # low cutoff frequency(Hz) - specified as 40bpm(~0.667Hz) in reference
        HPF = 2.5  # high cutoff frequency(Hz) - specified as 240bpm(~4.0Hz) in reference
        NyquistF = 15  # 15fps
        FS = 30  # 30fps
        B, A = signal.butter(3, [LPF / NyquistF, HPF / NyquistF], "bandpass")
        pulse_csi = (pulse_csi - np.min(pulse_csi)) / (np.max(pulse_csi) - np.min(pulse_csi))
        EXG2_f = signal.filtfilt(B, A, pulse_csi)
        EXG2_f = (EXG2_f - np.min(EXG2_f)) / (np.max(EXG2_f) - np.min(EXG2_f))

        # total_num_frame = 1800
        video_t = CSI_Time
        bvp = pulse_csi
        hr = np.full_like(bvp, 60)  # ! fake
        return video_t, bvp, hr


def save_crop_preview(frame, face, stored_face, cnt_x, cnt_y, bbox_size, preview_dir, frame_num):
    """Save the source bbox, raw crop, and final stored image for inspection."""
    os.makedirs(preview_dir, exist_ok=True)

    bbox_half_size = int(bbox_size / 2)
    raw_x1 = cnt_x - bbox_half_size
    raw_y1 = cnt_y - bbox_half_size
    x1 = max(0, raw_x1)
    y1 = max(0, raw_y1)
    x2 = min(frame.shape[1] - 1, raw_x1 + bbox_size - 1)
    y2 = min(frame.shape[0] - 1, raw_y1 + bbox_size - 1)

    bbox_frame = frame.copy()
    cv2.rectangle(bbox_frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

    previews = {
        "bbox": bbox_frame,
        "crop": face,
        "stored": stored_face,
    }
    for name, image in previews.items():
        output_path = os.path.join(preview_dir, f"{frame_num:04d}_{name}.jpg")
        cv2.imwrite(output_path, cv2.cvtColor(image, cv2.COLOR_RGB2BGR))


def openface_h5(
    dataset_name,
    video_path,
    landmark_path,
    json_path,
    h5_path,
    store_size=128,
    preview_frames=0,
):
    """
    crop face from OpenFace landmarks and save a video as .h5 file.

    video_path: the face video path
    landmark_path: landmark .csv file generated by OpenFace.
    h5_path: the path to save the h5_file
    store_size: the cropped face is resized to 128 (default).
    preview_frames: save crop previews for the first N frames. 0 disables it.
    """
    if preview_frames < 0:
        raise ValueError("preview_frames must be greater than or equal to 0.")
    preview_dir = os.path.splitext(h5_path)[0] + "_preview"

    if dataset_name == "UBFC-rPPG":
        landmark = pd.read_csv(landmark_path)

        with h5py.File(h5_path, "w") as f:
            total_num_frame = len(landmark)
            cap = cv2.VideoCapture(video_path)
            for frame_num in range(total_num_frame):
                if landmark["success"][frame_num]:
                    lm_x = []
                    lm_y = []
                    for lm_num in range(68):
                        lm_x.append(landmark["x_%d" % lm_num][frame_num])
                        lm_y.append(landmark["y_%d" % lm_num][frame_num])

                    lm_x = np.array(lm_x)
                    lm_y = np.array(lm_y)

                    minx = np.min(lm_x)
                    maxx = np.max(lm_x)
                    miny = np.min(lm_y)
                    maxy = np.max(lm_y)

                    y_range_ext = (maxy - miny) * 0.2
                    miny = miny - y_range_ext

                    cnt_x = np.round((minx + maxx) / 2).astype("int")
                    cnt_y = np.round((maxy + miny) / 2).astype("int")

                    break

            bbox_size = np.round(1.5 * (maxy - miny)).astype("int")

            # init dataset in h5
            if store_size == None:
                store_size = bbox_size

            imgs = f.create_dataset(
                "imgs",
                shape=(total_num_frame, store_size, store_size, 3),
                dtype="uint8",
                chunks=(1, store_size, store_size, 3),
                compression="gzip",
                compression_opts=4,
            )

            for frame_num in range(total_num_frame):
                if landmark["success"][frame_num]:
                    lm_x_ = []
                    lm_y_ = []
                    for lm_num in range(68):
                        lm_x_.append(landmark["x_%d" % lm_num][frame_num])
                        lm_y_.append(landmark["y_%d" % lm_num][frame_num])

                    lm_x_ = np.array(lm_x_)
                    lm_y_ = np.array(lm_y_)

                    lm_x = 0.9 * lm_x + 0.1 * lm_x_
                    lm_y = 0.9 * lm_y + 0.1 * lm_y_

                    minx = np.min(lm_x)
                    maxx = np.max(lm_x)
                    miny = np.min(lm_y)
                    maxy = np.max(lm_y)

                    y_range_ext = (maxy - miny) * 0.2
                    miny = miny - y_range_ext

                    cnt_x = np.round((minx + maxx) / 2).astype("int")
                    cnt_y = np.round((maxy + miny) / 2).astype("int")

                ret, frame = cap.read()
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

                if not ret:
                    print("Can't receive frame (stream end?). Exiting ...")
                    break

                # for bbox
                bbox_half_size = int(bbox_size / 2)

                face = np.take(frame, range(cnt_y - bbox_half_size, cnt_y - bbox_half_size + bbox_size), 0, mode="clip")
                face = np.take(face, range(cnt_x - bbox_half_size, cnt_x - bbox_half_size + bbox_size), 1, mode="clip")

                if store_size == bbox_size:
                    stored_face = face
                else:
                    stored_face = cv2.resize(face, (store_size, store_size))
                imgs[frame_num] = stored_face

                if frame_num < preview_frames:
                    save_crop_preview(
                        frame, face, stored_face, cnt_x, cnt_y,
                        bbox_size, preview_dir, frame_num
                    )

            cap.release()

            wave_t, bvp, hr = read_ground_truth(dataset_name, total_num_frame, json_path)

            # Add BVP to the existing .h5 file
            with h5py.File(h5_path, "a") as f:
                f.create_dataset("wave_t", data=wave_t)
                f.create_dataset("bvp", data=bvp)
                f.create_dataset("hr", data=hr)

    elif dataset_name == "PURE":
        landmark = pd.read_csv(landmark_path)

        with h5py.File(h5_path, "w") as f:

            total_num_frame = len(landmark)

            frame_names = sorted(os.listdir(video_path))
            frame_paths = [os.path.join(video_path, frame_name) for frame_name in frame_names]

            for frame_num in range(total_num_frame):
                if landmark["success"][frame_num]:
                    lm_x = []
                    lm_y = []
                    for lm_num in range(68):
                        lm_x.append(landmark["x_%d" % lm_num][frame_num])
                        lm_y.append(landmark["y_%d" % lm_num][frame_num])

                    lm_x = np.array(lm_x)
                    lm_y = np.array(lm_y)

                    minx = np.min(lm_x)
                    maxx = np.max(lm_x)
                    miny = np.min(lm_y)
                    maxy = np.max(lm_y)

                    y_range_ext = (maxy - miny) * 0.2
                    miny = miny - y_range_ext

                    cnt_x = np.round((minx + maxx) / 2).astype("int")
                    cnt_y = np.round((maxy + miny) / 2).astype("int")

                    break

            bbox_size = np.round(1.5 * (maxy - miny)).astype("int")

            # init dataset in h5
            if store_size == None:
                store_size = bbox_size

            imgs = f.create_dataset(
                "imgs",
                shape=(total_num_frame, store_size, store_size, 3),
                dtype="uint8",
                chunks=(1, store_size, store_size, 3),
                compression="gzip",
                compression_opts=4,
            )

            for frame_num in range(total_num_frame):
                if landmark["success"][frame_num]:
                    lm_x_ = []
                    lm_y_ = []
                    for lm_num in range(68):
                        lm_x_.append(landmark["x_%d" % lm_num][frame_num])
                        lm_y_.append(landmark["y_%d" % lm_num][frame_num])

                    lm_x_ = np.array(lm_x_)
                    lm_y_ = np.array(lm_y_)

                    lm_x = 0.9 * lm_x + 0.1 * lm_x_
                    lm_y = 0.9 * lm_y + 0.1 * lm_y_

                    minx = np.min(lm_x)
                    maxx = np.max(lm_x)
                    miny = np.min(lm_y)
                    maxy = np.max(lm_y)

                    y_range_ext = (maxy - miny) * 0.2
                    miny = miny - y_range_ext

                    cnt_x = np.round((minx + maxx) / 2).astype("int")
                    cnt_y = np.round((maxy + miny) / 2).astype("int")

                frame = cv2.imread(frame_paths[frame_num])
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

                # for bbox
                bbox_half_size = int(bbox_size / 2)

                face = np.take(frame, range(cnt_y - bbox_half_size, cnt_y - bbox_half_size + bbox_size), 0, mode="clip")
                face = np.take(face, range(cnt_x - bbox_half_size, cnt_x - bbox_half_size + bbox_size), 1, mode="clip")

                if store_size == bbox_size:
                    stored_face = face
                else:
                    stored_face = cv2.resize(face, (store_size, store_size))
                imgs[frame_num] = stored_face

                if frame_num < preview_frames:
                    save_crop_preview(
                        frame, face, stored_face, cnt_x, cnt_y,
                        bbox_size, preview_dir, frame_num
                    )

            wave_t, bvp, hr = read_ground_truth(dataset_name, total_num_frame, json_path)

            # Add BVP to the existing .h5 file
            with h5py.File(h5_path, "a") as f:
                f.create_dataset("wave_t", data=wave_t)
                f.create_dataset("bvp", data=bvp)
                f.create_dataset("hr", data=hr)

    elif dataset_name == "BUAA":
        landmark = pd.read_csv(landmark_path)
        with h5py.File(h5_path, "w") as f:
            total_num_frame = len(landmark)
            cap = cv2.VideoCapture(video_path)
            for frame_num in range(total_num_frame):
                if landmark["success"][frame_num]:
                    lm_x = []
                    lm_y = []
                    for lm_num in range(68):
                        lm_x.append(landmark["x_%d" % lm_num][frame_num])
                        lm_y.append(landmark["y_%d" % lm_num][frame_num])

                    lm_x = np.array(lm_x)
                    lm_y = np.array(lm_y)

                    minx = np.min(lm_x)
                    maxx = np.max(lm_x)
                    miny = np.min(lm_y)
                    maxy = np.max(lm_y)

                    y_range_ext = (maxy - miny) * 0.2
                    miny = miny - y_range_ext

                    cnt_x = np.round((minx + maxx) / 2).astype("int")
                    cnt_y = np.round((maxy + miny) / 2).astype("int")

                    break

            bbox_size = np.round(1.5 * (maxy - miny)).astype("int")

            # init dataset in h5
            if store_size == None:
                store_size = bbox_size

            imgs = f.create_dataset(
                "imgs",
                shape=(total_num_frame, store_size, store_size, 3),
                dtype="uint8",
                chunks=(1, store_size, store_size, 3),
                compression="gzip",
                compression_opts=4,
            )

            for frame_num in range(total_num_frame):
                if landmark["success"][frame_num]:
                    lm_x_ = []
                    lm_y_ = []
                    for lm_num in range(68):
                        lm_x_.append(landmark["x_%d" % lm_num][frame_num])
                        lm_y_.append(landmark["y_%d" % lm_num][frame_num])

                    lm_x_ = np.array(lm_x_)
                    lm_y_ = np.array(lm_y_)

                    lm_x = 0.9 * lm_x + 0.1 * lm_x_
                    lm_y = 0.9 * lm_y + 0.1 * lm_y_

                    minx = np.min(lm_x)
                    maxx = np.max(lm_x)
                    miny = np.min(lm_y)
                    maxy = np.max(lm_y)

                    y_range_ext = (maxy - miny) * 0.2
                    miny = miny - y_range_ext

                    cnt_x = np.round((minx + maxx) / 2).astype("int")
                    cnt_y = np.round((maxy + miny) / 2).astype("int")

                ret, frame = cap.read()
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

                if not ret:
                    print("Can't receive frame (stream end?). Exiting ...")
                    break

                # for bbox
                bbox_half_size = int(bbox_size / 2)

                face = np.take(frame, range(cnt_y - bbox_half_size, cnt_y - bbox_half_size + bbox_size), 0, mode="clip")
                face = np.take(face, range(cnt_x - bbox_half_size, cnt_x - bbox_half_size + bbox_size), 1, mode="clip")

                if store_size == bbox_size:
                    stored_face = face
                else:
                    stored_face = cv2.resize(face, (store_size, store_size))
                imgs[frame_num] = stored_face

                if frame_num < preview_frames:
                    save_crop_preview(
                        frame, face, stored_face, cnt_x, cnt_y,
                        bbox_size, preview_dir, frame_num
                    )

            cap.release()

            wave_t, bvp, hr = read_ground_truth(dataset_name, total_num_frame, json_path)

            # Add BVP to the existing .h5 file
            with h5py.File(h5_path, "a") as f:
                f.create_dataset("wave_t", data=wave_t)
                f.create_dataset("bvp", data=bvp)
                f.create_dataset("hr", data=hr)


def main():
    args = parser.parse_args()
    suffix = f"_s{args.store_size}" if args.store_size is not None else ""
    if args.dataset_name == "UBFC-rPPG":
        subjects = sorted(os.listdir(args.video_dir))
        print("subjects:", subjects)
        print("number of subjects:", len(subjects))

        for subject in tqdm(subjects, desc="subject"):
            video_path = os.path.join(args.video_dir, subject, "vid.avi")
            landmark_path = os.path.join(args.landmark_dir, subject, "vid.csv")
            json_path = os.path.join(args.json_dir, subject, "ground_truth.txt")
            h5_path = os.path.join(args.h5_dir, subject, f"vid{suffix}.h5")

            h5_subdir = os.path.join(args.h5_dir, subject)
            if not os.path.exists(h5_subdir):
                os.makedirs(h5_subdir)

            openface_h5(
                args.dataset_name,
                video_path,
                landmark_path,
                json_path,
                h5_path,
                store_size=args.store_size,
                preview_frames=args.preview_frames,
            )

    elif args.dataset_name == "PURE":
        sessions = sorted(os.listdir(args.video_dir))
        print("sessions:", sessions)
        print("number of sessions:", len(sessions))

        for session in tqdm(sessions, desc="session"):
            video_path = os.path.join(args.video_dir, session, session)
            landmark_path = os.path.join(args.landmark_dir, session, session + ".csv")
            json_path = os.path.join(args.json_dir, session, session + ".json")
            h5_path = os.path.join(args.h5_dir, session, f"{session}{suffix}.h5")

            h5_subdir = os.path.join(args.h5_dir, session)
            if not os.path.exists(h5_subdir):
                os.makedirs(h5_subdir)

            openface_h5(
                args.dataset_name,
                video_path,
                landmark_path,
                json_path,
                h5_path,
                store_size=args.store_size,
                preview_frames=args.preview_frames,
            )

    elif args.dataset_name == "BUAA":
        subject_folders = get_subfolders(args.video_dir)
        print("number of subjects:", len(subject_folders))
        for subject_folder in tqdm(subject_folders, desc="subject"):
            subject = os.path.basename(subject_folder)

            session_folders = get_subfolders(subject_folder)
            for session_folder in session_folders:
                session = os.path.basename(session_folder)
                if session not in ["lux_10.0", "lux_15.8", "lux_25.1", "lux_39.8", "lux_63.1", "lux_100.0"]:
                    continue

                video_paths = [os.path.join(session_folder, f) for f in os.listdir(session_folder) if f.endswith(".avi")]
                if not video_paths:
                    print(f"There are no .avi files in {session_folder}.")

                video_path = video_paths[0]
                video_name = os.path.basename(video_path)
                video_name = os.path.splitext(video_name)[0]

                landmark_path = os.path.join(args.landmark_dir, subject, session, video_name + ".csv")
                json_path = os.path.join(args.json_dir, subject, session)
                h5_path = os.path.join(args.h5_dir, subject, session, f"{video_name}{suffix}.h5")

                h5_subdir = os.path.join(args.h5_dir, subject, session)
                if not os.path.exists(h5_subdir):
                    os.makedirs(h5_subdir)

                PPGData_mat = os.path.join(json_path, "PPGData.mat")
                # Check if the file exists
                if not os.path.exists(PPGData_mat):
                    continue

                openface_h5(
                    args.dataset_name,
                    video_path,
                    landmark_path,
                    json_path,
                    h5_path,
                    store_size=args.store_size,
                    preview_frames=args.preview_frames,
                )


if __name__ == "__main__":
    main()
